openapi: 3.0.1
info:
  title: ConsumeInvendaApi
  description: API Definition of ConsumeInvendaApi
  version: 1.0.0
servers:
- url: http://localhost:8290/invenda/consume
paths:
  /transactions:
    get:
      responses:
        default:
          description: Default response
